### ISSUE TITLE
Improvements to component workflow

### ISSUE THREAD

**Issue by jens1101** [jens1101/mini-pomodoro#24]
Currently the way I build web components is not enforced in any way. I use the `jt-component` library as a helper, but it isn't enforcing any style. It would be better to find a way to enforce certain rules for components, especially when the user makes use of the `jt-component` library.

# Suggestions
- Make `JtComponent` a class that extends `HTMLElement`. Anything wanting to make use of `JtComponent` must extend it. Thus we can add functionality in there which is well documented and can be enforced to anything that inherits from it.

**Comment by jens1101** [comment]
# Suggestions
- Add a lifecycle callback function which is triggered once the component setup is complete

# TODO
- [ ] Make `JtComponent` a class that extends `HTMLElement`. Anything wanting to make use of `JtComponent` must extend it. Thus we can add functionality in there which is well documented and can be enforced to anything that inherits from it.
- [ ] Add default component behaviour to enforce a certain style
- [ ] Maintain the option for valid HTML
